### ISSUE TITLE
Update to using Firebase Storage

### ISSUE THREAD

**Issue by asciimike** [davideast/iOS-Firebase-Pokedex#1]
We should update this repo to use Firebase Storage or remove it, since we don't want people to base64 encode things any more.

**Comment by faizandedia** [comment]
Is it good practice to store images as base64 or use FirebaseStorage?

**Comment by asciimike** [comment]
@faizandedia you should definitely use [Firebase Storage](https://firebase.google.com/docs/storage/ios/start). Prior to I/O 2016 (May 18th of this year), we didn't have file storage, so we had to base64 encode images, or upload them to a third party service, but now that we have Firebase Storage, this is the recommended best practice.

**Comment by faizandedia** [comment]
@mcdonamp  Thankyou for the response. :)
